[workspace]
members = [
    "crates/*"
]

[package]
name = "eval"
version = "0.1.0"
edition = "2021"

[dependencies]
eval_parser = { path = "crates/eval_parser" }
eval_ast = { path = "crates/eval_ast" }
eval_compiler = { path = "crates/eval_compiler" }
eval_vm = { path = "crates/eval_vm" }
